Release version v0.373.0
  - [467546154][INFRA] Migrate some cc_utils to blzmod
  - [476520269][INFRA] Fix Curl Client data corruption
  - [454480355][KS] Remove legacy keys
  - [477387487][INFRA] Tag integration tests that timeout as ...
  - [455849755][KS] Add terraform variables for migrating LB ...

GitOrigin-RevId: 5ecf2d4f060ad19e37310c531d2cc39110234252
Change-Id: Ie9215a6c2477f3f8621cb00896d3b06bcf4d6813

diff --git a/cc/proxy/parent_instance/aws/al2023/BUILD b/cc/proxy/parent_instance/aws/al2023/BUILD
--- a/cc/proxy/parent_instance/aws/al2023/BUILD
+++ b/cc/proxy/parent_instance/aws/al2023/BUILD
@@ -38,27 +38,50 @@ genrule(
         "proxy",
     ],
     cmd = """
+    cp `realpath $(location //:source_code.tar)` ./
+    cp `realpath $(location @bazelisk//file:bazelisk)` ./
+
     export OUTPUT_DIR=`mktemp -d -t PROXY_BUILD_OUTPUTS_XXXXX`
     docker load < $(location :build_container_al2023.tar)
-    docker run --rm \
-      -v `realpath $(location //:source_code.tar)`:/source_code.tar \
-      -v `realpath $(location @bazelisk//file:bazelisk)`:/bin/bazel \
-      -v `realpath "$${OUTPUT_DIR}"`:/output \
+
+    rand_container_id=proxy-build-container-`head /dev/urandom | tr -dc A-Za-z0-9 | head -c 32`
+    echo "Starting container $${rand_container_id}"
+    # Make sure container is killed if build fails
+    trap "docker rm -f $${rand_container_id} > /dev/null 2> /dev/null" ERR
+
+    docker run -d --name $${rand_container_id} \
       bazel/cc/proxy/parent_instance/aws/al2023:build_container_al2023 \
       bash -c '
+        tail -f /dev/null
+      '
+    # Copy artifacts into container and make sure container user has access to them
+    docker cp `realpath source_code.tar` $${rand_container_id}:/source_code.tar
+    docker cp `realpath bazelisk` $${rand_container_id}:/bin/bazel
+
+    # Run dependency install as root within container and change file ownership to bazel sandbox user
+    docker exec $${rand_container_id} bash -c '
         set -eux
         dnf install glibc-devel-2.34-52.amzn2023.0.3 clang-15.0.6-3.amzn2023.0.2 tar git -y > /dev/null
-        tar xf /source_code.tar -C /
-        ls
-        cd /scp
+      '
+    # Build proxy and copy proxy artifact to output dir
+    docker exec \
+      $${rand_container_id}  \
+      bash -c '
+        set -eux
+        tar xf /source_code.tar -C /tmp
+        cd /tmp/scp
         export CXX=/usr/bin/clang++-15
         export CC=/usr/bin/clang-15
+        mkdir /tmp/proxy_build_output
         bazel build \
           //cc/proxy/src:proxy
-        cp $$(bazel info bazel-bin)/cc/proxy/src/proxy /output
+        cp $$(bazel info bazel-bin)/cc/proxy/src/proxy /tmp/proxy_build_output
       '
+    docker cp $${rand_container_id}:/tmp/proxy_build_output/proxy $${OUTPUT_DIR}
+
     cp "$${OUTPUT_DIR}/proxy" $(location proxy)
     rm -r "$${OUTPUT_DIR}"
+    docker rm -f $${rand_container_id} > /dev/null 2> /dev/null
     """,
     tags = ["manual"],
 )
diff --git a/cc/proxy/tee/debian/debian11/BUILD b/cc/proxy/tee/debian/debian11/BUILD
--- a/cc/proxy/tee/debian/debian11/BUILD
+++ b/cc/proxy/tee/debian/debian11/BUILD
@@ -13,61 +13,14 @@
 # limitations under the License.
 
 load("@io_bazel_rules_docker//container:container.bzl", "container_image")
-load("@io_bazel_rules_docker//docker/package_managers:download_pkgs.bzl", "download_pkgs")
-load("@io_bazel_rules_docker//docker/package_managers:install_pkgs.bzl", "install_pkgs")
-load("@io_bazel_rules_docker//docker/util:run.bzl", "container_run_and_commit_layer")
 
 package(
     default_visibility = ["//visibility:public"],
 )
 
-download_pkgs(
-    name = "debian11_build_apt_pkgs_download",
-    image_tar = "@debian_11//image",
-    packages = [
-        "ca-certificates",
-        "clang-13",
-        "git",
-        "tar",
-    ],
-    tags = ["manual"],
-)
-
-install_pkgs(
-    name = "debian11_build_apt_pkgs_install",
-    image_tar = "@debian_11//image",
-    installables_tar = ":debian11_build_apt_pkgs_download.tar",
-    output_image_name = "debian11_build_apt_pkgs_install",
-    tags = ["manual"],
-)
-
-container_image(
-    name = "build_container_debian11_base",
-    base = "debian11_build_apt_pkgs_install.tar",
-    tags = ["manual"],
-)
-
-container_run_and_commit_layer(
-    name = "container_to_build_debian11_bazel",
-    commands = [
-        "ln -s /usr/bin/clang-13 /usr/bin/clang",
-        "ln -s /usr/bin/clang++-13 /usr/bin/clang++",
-        "ln -s /usr/bin/clang-cpp-13 /usr/bin/clang-cpp",
-    ],
-    env = {
-        "CC": "/usr/bin/clang",
-        "CXX": "/usr/bin/clang++",
-    },
-    image = ":debian11_build_apt_pkgs_install.tar",
-    tags = ["manual"],
-)
-
 container_image(
     name = "build_container_debian11",
-    base = "build_container_debian11_base.tar",
-    layers = [
-        ":container_to_build_debian11_bazel",
-    ],
+    base = "@debian_11//image",
     tags = ["manual"],
 )
 
@@ -85,27 +38,54 @@ genrule(
     ],
     cmd = """
     export OUTPUT_DIR=`mktemp -d -t PROXY_BUILD_OUTPUTS_XXXXX`
+
+    cp `realpath $(location //:source_code.tar)` ./
+    cp `realpath $(location @bazelisk//file:bazelisk)` ./
+
     docker load < $(location :build_container_debian11.tar)
-    docker run --rm \
-      -v `realpath $(location //:source_code.tar)`:/source_code.tar \
-      -v `realpath $(location @bazelisk//file:bazelisk)`:/bin/bazel \
-      -v `realpath "$${OUTPUT_DIR}"`:/output \
+
+    rand_container_id=proxy-debian-build-container-`head /dev/urandom | tr -dc A-Za-z0-9 | head -c 32`
+    echo "Starting container $${rand_container_id}"
+    # Make sure container is killed if build fails
+    trap "docker rm -f $${rand_container_id} > /dev/null 2> /dev/null" ERR
+
+    docker run -d --name $${rand_container_id} \
       bazel/cc/proxy/tee/debian/debian11:build_container_debian11 \
       bash -c '
-        set -eux
-        tar xf /source_code.tar -C /
-        ls
-        cd /scp
+        tail -f /dev/null
+      '
+
+    # Copy artifacts into container and make sure container user has access to them
+    docker cp `realpath source_code.tar` $${rand_container_id}:/source_code.tar
+    docker cp `realpath bazelisk` $${rand_container_id}:/bin/bazel
+
+    # Build proxy and copy proxy artifacts to output dir
+    docker exec \
+      $${rand_container_id}  \
+      bash -c '
+        set -ex
+        apt-get update && apt-get install -y ca-certificates clang-13 git tar
+        export CC="/usr/bin/clang-13"
+        export CXX="/usr/bin/clang++-13"
+        tar xf /source_code.tar -C /tmp
+        cd /tmp/scp
+        mkdir /tmp/proxy_build_output
         bazel build \
           //cc/proxy/src:proxify \
           //cc/proxy/src:proxy_preload \
           //cc/proxy/src:socket_vendor
-        cp $$(bazel info bazel-bin)/cc/proxy/src/{libproxy_preload.so,proxify,socket_vendor} /output
+        cp $$(bazel info bazel-bin)/cc/proxy/src/{libproxy_preload.so,proxify,socket_vendor} /tmp/proxy_build_output
       '
+
+    docker cp $${rand_container_id}:/tmp/proxy_build_output/libproxy_preload.so $${OUTPUT_DIR}
+    docker cp $${rand_container_id}:/tmp/proxy_build_output/proxify $${OUTPUT_DIR}
+    docker cp $${rand_container_id}:/tmp/proxy_build_output/socket_vendor $${OUTPUT_DIR}
+
     cp "$${OUTPUT_DIR}/libproxy_preload.so" $(location libproxy_preload.so)
     cp "$${OUTPUT_DIR}/proxify" $(location proxify)
     cp "$${OUTPUT_DIR}/socket_vendor" $(location socket_vendor)
     rm -r "$${OUTPUT_DIR}"
+    docker rm -f $${rand_container_id} > /dev/null 2> /dev/null
     """,
     tags = ["manual"],
 )
